### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by Partha-2000-Snp** [Partha-2000-Snp/2418-login#1]
create login page with following requirements.
1. two text box for username and password.
2. set avatar image for the page
3. remember me check box
4. forget password link

![img_avatar2](https://github.com/user-attachments/assets/06570e91-a039-40c3-88d5-5e540f504377)
![login page dev team ref image](https://github.com/user-attachments/assets/51bb09a7-64da-45e5-9848-acff01e3c422)

**Comment by ParthasarathiPanda** [comment]
i am done with the work and waiting for approval and marge. pull request has been raised.

**Comment by Partha-2000-Snp** [comment]
approved and merged. closing the case.
