### ISSUE TITLE
Create a registration page for the user.

### ISSUE THREAD

**Issue by Partha-2000-Snp** [Partha-2000-Snp/2418-login#3]
Create a registration page for the user.
it must contains 2 text box
username and password

make sure that the user repeat the password for confirmation.

**Comment by Parthasarathi-P** [comment]
working on it

**Comment by Partha-2000-Snp** [comment]
page was submitted. but deleted as discussed by developer and admin. further changes will be done soon.

**Comment by Partha-2000-Snp** [comment]
completed
